[project]
name = 'stake-stream'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.stake-stream]
path = 'contracts/stake-stream.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
